from graphics import *
rad1=float(input("Enter the radius of the circle: "))
print("Area of circle is",area(rad1))
print("Perimeter of circle is",perimeter(rad1))
len1=float(input("Enter the length of the rectangle: "))
breadth1=float(input("Enter the breadth of the rectangle: "))
len2=float(input("Enter the length of the cuboid: "))
breadth2=float(input("Enter the breadth of the cuboid: "))
height=float(input("Enter the height of the cuboid: "))
rad2=float(input("Enter the radius of the sphere: "))
